export enum REDUX_ACTIONS {
    ORDERS_UPDATE = 'ORDERS_UPDATE',
    ACTIVE_CURRENCY_UPDATE = 'ACTIVE_CURRENCY_UPDATE',
    ALL_CATEGORIES_UPDATE = 'ALL_CATEGORIES_UPDATE',
    ACTIVE_CATEGORY_UPDATE = 'ACTIVE_CATEGORY_UPDATE',
    CURRENCY_DROPDOWN_STATUS_TOGGLE = 'CURRENCY_DROPDOWN_STATUS_TOGGLE',
}